name: Initial Tests

on:
  push:  # Specifies the action  that will trigger  this job
    branches: [master]

jobs:
  say-hello:
    runs-on: ubuntu-latest # Specifies the operating system for the job
    steps:
      - name: Print Hello World
        run: echo "Hello, World!" # The command to execute
      - name: Check server URL
        run: |
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
