name: Initial Tests

on:
  push:  # Specifies the action  that will trigger  this job
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest # Specifies the operating system for the job
    steps:
      - name: Print Hello World
        run: echo "Hello, World!" # The command to execute
